spring: 
  application: 
    name: spring-cloud-producer
server: 
  port: 9001
  
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://peer1:8000/eureka/, http://peer2:8001/eureka/
#      register-with-eureka: false
#      fetch-registry: false

