spring: 
  application: 
    name: hystrix-dashboard-turbine
server: 
  port: 22001
  
eureka: 
  instance: 
    hostname: peer2
  client: 
    serviceUrl: 
      defaultZone: http://peer1:20000/eureka/,http://peer2:20001/eureka/
#      register-with-eureka: false
#      fetch-registry: false


turbine: 
  appConfig: spring-cloud-client-b
  aggregator: 
    clusterConfig: default
  clusterNameExpression: new String("default")
