server:
  port: 23001
spring:
  application:
    name: testspring-git-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/caishuai163/spring-cloud-test.git     # 配置git仓库的地址
          search-paths: configs                      # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: caishuai_cs@163.com                 # git仓库的账号
          password: caishuai123                         # git仓库的密码