spring: 
  application: 
    name: gateway-service-zuul
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      percentage: 1.0
server: 
  port: 24001 # the port never changed if the application not restart

# eureka register config 
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://peer1:20000/eureka/,http://peer2:20001/eureka/
#      register-with-eureka: false
#      fetch-registry: false
