spring: 
  application: 
    name: spring-cloud-client-c
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      percentage: 1.0
server: 
  port: 21003
  
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://peer1:20000/eureka/, http://peer2:20001/eureka/
#      register-with-eureka: false
#      fetch-registry: false

feign:
  hystrix:
    # 熔断开关
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: refresh

my: 
  key: 123456
