spring: 
  application: 
    name: spring-cloud-client-b
  cloud: 
    consul: 
      host: 10.12.54.206
      port: 8500
      discovery: 
        serviceName: ${spring.application.name}
server: 
  port: 21002 

feign:
  hystrix:
    # 熔断开关
    enabled: true
    
# why add, see http://www.mamicode.com/info-detail-2291907.html or see https://yq.aliyun.com/articles/635815    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,refresh # 支持获取熔断状态，支持刷新配置
 
 # 项目内配置
call: 
  client: 
    name: 
      c: spring-cloud-client-c

